-- Part D: Drop tables

DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS ItemCategory;
DROP TABLE IF EXISTS ItemBuyPrice;
DROP TABLE IF EXISTS Bid;
DROP TABLE IF EXISTS UserLocation;
DROP TABLE IF EXISTS BidderRating;
DROP TABLE IF EXISTS SellerRating;
DROP TABLE IF EXISTS ItemLocation;
